name: Python script and Test Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:  # This allows the action to be run manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r stories/date/requirement.txt

    - name: Run Python scripts
      run: |
        python stories/date/scripts/autobiographies.py
        python stories/date/scripts/daybooks.py
        python stories/date/scripts/journals.py

    - name: Run Python tests
      run: |
        python -m unittest discover -s stories/date/test -p '*Test.py'
      
    - name: Copy CSV files
      run: |
        mkdir -p data/artifact/date
        cp stories/date/data/*.csv data/artifact/date
      
    - name: Setup Git and push
      env:
        GH_TOKEN: ${{ secrets.TYLER_PAT }} 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add data files"
        git push https://${GH_TOKEN}@github.com/wilfordwoodruff/Engineering_Repo.git HEAD:main


  copy_to_main_data:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: wilfordwoodruff/Main-Data
        token: ${{ secrets.TYLER_PAT }}
        path: Main-Data

    - name: Copy CSV files to Main-Data repository
      run: |
        cp data/artifact/date/*.csv Main-Data/data/artifact/date

    - name: Commit and push CSV files to Main-Data repository
      run: |
        cd Main-Data
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/artifact/date/*.csv
        git commit -m "Add data files"
        git push
