name: Jupyter Notebook Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:  # This allows the action to be run manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r stories/location/requirement.txt

    - name: Install Jupyter
      run: |
        pip install jupyter

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --execute stories/location/scripts/e_location.ipynb
